import { FormBuilder, FormControl } from '@angular/forms';
import { Component } from '@angular/core';
import { QueryBuilderConfig, QueryBuilderClassNames } from "angular2-query-builder";

declare const __moduleName: string;

@Component({
    selector: 'my-app',
    moduleId: __moduleName,
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent {
    public queryCtrl: FormControl;

    public bootstrapClassNames: QueryBuilderClassNames = {
        removeIcon: 'fa fa-minus',
        addIcon: 'fa fa-plus',
        button: 'btn',
        buttonGroup: 'btn-group',
        rightAlign: 'order-12 ml-auto',
        switchRow: 'd-flex px-2',
        switchGroup: 'd-flex align-items-center',
        switchRadio: 'custom-control-input',
        switchLabel: 'custom-control-label',
        switchControl: 'custom-control custom-radio custom-control-inline',
        row: 'row p-2 m-1',
        rule: 'border',
        ruleSet: 'border',
        invalidRuleSet: 'alert alert-danger',
        emptyWarning: 'text-danger mx-auto',
        operatorControl: 'form-control',
        operatorControlSize: 'col-auto pr-0',
        fieldControl: 'form-control',
        fieldControlSize: 'col-auto pr-0',
        entityControl: 'form-control',
        entityControlSize: 'col-auto pr-0',
        inputControl: 'form-control',
        inputControlSize: 'col-auto'
    };

    public query = {
        condition: 'and',
        rules: [
            { field: 'age', operator: '<=' }
        ]
    };

    public config: QueryBuilderConfig = {
        fields: {
            age: { name: 'Age', type: 'number' },
            AGER_TYP: { name: 'best-ager typology', type: 'number' },
            D19_BANKEN_DIREKT_RZ: { name: 'transactional activity based on the product group DIRECT BANKS', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_BANKEN_GROSS_RZ: { name: 'transactional activity based on the product group LARGE BANKS', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_BANKEN_LOKAL_RZ: { name: 'transactional activity based on the product group LOCAL BANKS ', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_BANKEN_REST_RZ: { name: 'transactional activity based on the product group FURTHER BANKS', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_BEKLEIDUNG_GEH_RZ: { name: 'transactional activity based on the product group LUXURY CLOTHING', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_BEKLEIDUNG_REST_RZ: { name: 'transactional activity based on the product group FURTHER CLOTHING', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_BIO_OEKO_RZ: { name: 'transactional activity based on the product group BIO FOOD PRODUCTS', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_BILDUNG_RZ: { name: 'transactional activity based on the product group EDUCATION', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_BUCH_RZ: { name: 'transactional activity based on the product group BOOKS ', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_DIGIT_SERV_RZ: { name: 'transactional activity based on the product group DIGITAL SERVICE', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_DROGERIEARTIKEL_RZ: { name: 'transactional activity based on the product group DRUGSTORE PRODUCTS', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_ENERGIE_RZ: { name: 'transactional activity based on the product group ENERGY', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_FREIZEIT_RZ: { name: 'transactional activity based on the product group LEISURE PRODUCTS ', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_GARTEN_RZ: { name: 'transactional activity based on the product group GARDEN', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_HANDWERK_RZ: { name: 'transactional activity based on the product group DO-IT-YOURSELF PRODUCTS ', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_HAUS_DEKO_RZ: { name: 'transactional activity based on the product group HOUSE DECORATION', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_KINDERARTIKEL_RZ: { name: 'transactional activity based on the product group CHILDREN´S PRODUCTS ', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_KOSMETIK_RZ: { name: 'transactional activity based on the product group COSMETIC PRODUCTS', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_LEBENSMITTEL_RZ: { name: 'transactional activity based on the product group FOOD PRODUCTS', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_NAHRUNGSERGAENZUNG_RZ: { name: 'transactional activity based on the product group DIETARY SUPPLEMENTS', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_RATGEBER_RZ: { name: 'transactional activity based on the product group GUIDEBOOKS', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_REISEN_RZ: { name: 'transactional activity based on the product group TRAVEL RELATED PRODUCTS', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_SAMMELARTIKEL_RZ: { name: 'transactional activity based on the product group COLLECTORS ITEMS ', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_SCHUHE_RZ: { name: 'transactional activity based on the product group SHOES', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_SONSTIGE_RZ: { name: 'transactional activity based on the product group ALL OTHER CATEGORIES ', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_TECHNIK_RZ: { name: 'transactional activity based on the product group TECHNOLOGY', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_TELKO_MOBILE_RZ: { name: 'transactional activity based on the product group MOBILE COMMUNICATION', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_TELKO_REST_RZ: { name: 'transactional activity based on the product group FURTHER MOBILE TELECOMMUNICATION PRODUCTS', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_TIERARTIKEL_RZ: { name: 'transactional activity based on the product group ANIMAL PRODUCTS', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_VERSICHERUNGEN_RZ: { name: 'transactional activity based on the product group INSURANCE', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_VOLLSORTIMENT_RZ: { name: 'transactional activity based on the product group COMPLETE MAIL-ORDER OFFERS', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_VERSAND_REST_RZ: { name: 'transactional activity based on the product group FURTHER MAIL-ORDER ARTICLES', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            D19_WEIN_FEINKOST_RZ: { name: 'transactional activity based on the product group WINE AND GOURMET FOOD', type: 'category', options: [{ name: 'High', value: '3' }, { name: 'Medium', value: '2' }, { name: 'Low', value: '1' }] },
            ALTERSKATEGORIE_GROB: { name: 'age classification through prename analysis ', type: 'number' },
            ALTER_HH: { name: 'main age within the household', type: 'number' },
            ANREDE_KZ: { name: 'gender', type: 'number' },
            ANZ_HAUSHALTE_AKTIV: { name: 'number of households in the building', type: 'number' },
            ANZ_HH_TITEL: { name: 'number of academic title holder in building', type: 'number' },
            ANZ_PERSONEN: { name: 'number of adult persons in the household', type: 'number' },
            ANZ_TITEL: { name: 'number of professional title holder in household ', type: 'number' },
            BALLRAUM: { name: 'distance to next urban centre ', type: 'number' },
            CAMEO_DEUG_2015: { name: 'CAMEO classification 2015 - Uppergroup', type: 'number' },
            CJT_GESAMTTYP: { name: 'customer journey typology', type: 'number' },
            D19_BANKEN_ANZ_12: { name: 'transaction activity BANKS in the last 12 months', type: 'number' },
            D19_BANKEN_ANZ_24: { name: 'transaction activity BANKS in the last 24 months', type: 'number' },
            D19_BANKEN_DATUM: { name: 'actuality of the last transaction for the segment banks TOTAL', type: 'number' },
            D19_BANKEN_OFFLINE_DATUM: { name: 'actuality of the last transaction for the segment banks OFFLINE', type: 'number' },
            D19_BANKEN_ONLINE_DATUM: { name: 'actuality of the last transaction for the segment banks ONLINE', type: 'number' },
            D19_GESAMT_ANZ_12: { name: 'transaction activity TOTAL POOL in the last 12 months ', type: 'number' },
            D19_GESAMT_ANZ_24: { name: 'transaction activity TOTAL POOL in the last 24 months ', type: 'number' },
            D19_GESAMT_DATUM: { name: 'actuality of the last transaction with the complete file TOTAL', type: 'number' },
            D19_GESAMT_OFFLINE_DATUM: { name: 'actuality of the last transaction with the complete file OFFLINE', type: 'number' },
            D19_GESAMT_ONLINE_DATUM: { name: 'actuality of the last transaction with the complete file ONLINE', type: 'number' },
            D19_TELKO_ANZ_12: { name: 'transaction activity TELCO in the last 12 months', type: 'number' },
            D19_TELKO_ANZ_24: { name: 'transaction activity TELCO in the last 24 months', type: 'number' },
            D19_TELKO_DATUM: { name: 'actuality of the last transaction for the segment telecommunication TOTAL', type: 'number' },
            D19_TELKO_OFFLINE_DATUM: { name: 'actuality of the last transaction for the segment telecommunication OFFLINE', type: 'number' },
            D19_TELKO_ONLINE_DATUM: { name: 'actuality of the last transaction for the segment telecommunication ONLINE', type: 'number' },
            D19_VERSAND_ANZ_12: { name: 'transaction activity MAIL-ORDER in the last 12 months', type: 'number' },
            D19_VERSAND_ANZ_24: { name: 'transaction activity MAIL-ORDER in the last 24 months', type: 'number' },
            D19_VERSAND_DATUM: { name: 'actuality of the last transaction for the segment mail-order TOTAL', type: 'number' },
            D19_VERSAND_OFFLINE_DATUM: { name: 'actuality of the last transaction for the segment mail-order OFFLINE', type: 'number' },
            D19_VERSAND_ONLINE_DATUM: { name: 'actuality of the last transaction for the segment mail-order ONLINE', type: 'number' },
            D19_VERSI_ANZ_12: { name: 'transaction activity INSURANCE in the last 12 months', type: 'number' },
            D19_VERSI_ANZ_24: { name: 'transaction activity INSURANCE in the last 24 months', type: 'number' },
            EWDICHTE: { name: 'density of inhabitants per square kilometer', type: 'number' },
            FINANZTYP: { name: 'best descirbing financial type for the person', type: 'number' },
            FINANZ_ANLEGER: { name: 'financial typology: investor', type: 'number' },
            FINANZ_HAUSBAUER: { name: 'financial typology: main focus is the own house', type: 'number' },
            FINANZ_MINIMALIST: { name: 'financial typology: low financial interest', type: 'number' },
            FINANZ_SPARER: { name: 'financial typology: money saver', type: 'number' },
            FINANZ_UNAUFFAELLIGER: { name: 'financial typology: unremarkable', type: 'number' },
            FINANZ_VORSORGER: { name: 'financial typology: be prepared', type: 'number' },
            GEBAEUDETYP: { name: 'type of building (residential or commercial)', type: 'number' },
            HEALTH_TYP: { name: 'health typology', type: 'number' },
            HH_EINKOMMEN_SCORE: { name: 'estimated household net income ', type: 'number' },
            INNENSTADT: { name: 'distance to the city centre', type: 'number' },
            KBA05_ALTER1: { name: 'share of car owners less than 31 years old', type: 'number' },
            KBA05_ALTER2: { name: 'share of car owners inbetween 31 and 45 years of age', type: 'number' },
            KBA05_ALTER3: { name: 'share of car owners inbetween 45 and 60 years of age', type: 'number' },
            KBA05_ALTER4: { name: 'share of cars owners elder than 61 years', type: 'number' },
            KBA05_ANHANG: { name: 'share of trailers in the microcell', type: 'number' },
            KBA05_ANTG1: { name: 'number of 1-2 family houses in the cell', type: 'number' },
            KBA05_ANTG2: { name: 'number of 3-5 family houses in the cell', type: 'number' },
            KBA05_ANTG3: { name: 'number of 6-10 family houses in the cell', type: 'number' },
            KBA05_ANTG4: { name: 'number of >10 family houses in the cell', type: 'number' },
            KBA05_AUTOQUOT: { name: 'share of cars per household', type: 'number' },
            CAMEO_DEU_2015: { name: 'most common building-type within the cell', type: 'number' },
            KBA05_CCM1: { name: 'share of cars with less than 1399ccm', type: 'number' },
            KBA05_CCM2: { name: 'share of cars with 1400ccm to 1799 ccm', type: 'number' },
            KBA05_CCM3: { name: 'share of cars with 1800ccm to 2499 ccm', type: 'number' },
            KBA05_CCM4: { name: 'share of cars with more than 2499ccm', type: 'number' },
            KBA05_DIESEL: { name: 'share of cars with Diesel-engine in the microcell', type: 'number' },
            KBA05_FRAU: { name: 'share of female car owners', type: 'number' },
            KBA05_GBZ: { name: 'number of buildings in the microcell', type: 'number' },
            KBA05_HERST1: { name: 'share of top German manufacturer (Mercedes, BMW) ', type: 'number' },
            KBA05_HERST2: { name: 'share of Volkswagen-Cars (including Audi)', type: 'number' },
            KBA05_HERST3: { name: 'share of Ford/Opel', type: 'number' },
            KBA05_HERST4: { name: 'share of European manufacturer (e.g. Fiat, Peugeot, Rover,...)', type: 'number' },
            KBA05_HERST5: { name: 'share of asian manufacturer (e.g. Toyota, Kia,...)', type: 'number' },
            KBA05_HERSTTEMP: { name: 'development of the most common car manufacturers in the neighbourhood', type: 'number' },
            KBA05_KRSAQUOT: { name: 'share of cars per household (reffered to county average)', type: 'number' },
            KBA05_KRSHERST1: { name: 'share of Mercedes/BMW (reffered to the county average)', type: 'number' },
            KBA05_KRSHERST2: { name: 'share of Volkswagen (reffered to the county average)', type: 'number' },
            KBA05_KRSHERST3: { name: 'share of Ford/Opel (reffered to the county average)', type: 'number' },
            KBA05_KRSKLEIN: { name: 'share of small cars (referred to the county average)', type: 'number' },
            KBA05_KRSOBER: { name: 'share of upper class cars (referred to the county average)', type: 'number' },
            KBA05_KRSVAN: { name: 'share of vans (referred to the county average)', type: 'number' },
            KBA05_KRSZUL: { name: 'share of newbuilt cars (referred to the county average)', type: 'number' },
            KBA05_KW1: { name: 'share of cars with less than 59 KW engine power', type: 'number' },
            KBA05_KW2: { name: 'share of cars with an engine power between 60 and 119 KW', type: 'number' },
            KBA05_KW3: { name: 'share of cars with an engine power of more than 119 KW', type: 'number' },
            KBA05_MAXAH: { name: 'most common age of car owners in the microcell', type: 'number' },
            KBA05_MAXBJ: { name: 'most common age of the cars in the microcell', type: 'number' },
            KBA05_MAXHERST: { name: 'most common car manufacturer in the microcell', type: 'number' },
            KBA05_MAXSEG: { name: 'most common car segment in the microcell', type: 'number' },
            KBA05_MAXVORB: { name: 'most common preowner structure in the microcell', type: 'number' },
            KBA05_MOD1: { name: 'share of upper class cars (in an AZ specific definition)', type: 'number' },
            KBA05_MOD2: { name: 'share of middle class cars (in an AZ specific definition)', type: 'number' },
            KBA05_MOD3: { name: 'share of Golf-class cars (in an AZ specific definition)', type: 'number' },
            KBA05_MOD4: { name: 'share of small cars (in an AZ specific definition)', type: 'number' },
            KBA05_MOD8: { name: 'share of vans (in an AZ specific definition)', type: 'number' },
            KBA05_MODTEMP: { name: 'development of the most common car segment in the neighbourhood', type: 'number' },
            KBA05_MOTOR: { name: 'most common engine size in the microcell', type: 'number' },
            KBA05_MOTRAD: { name: 'share of motorcycles per household', type: 'number' },
            KBA05_SEG1: { name: 'share of very small cars (Ford Ka etc.) in the microcell', type: 'number' },
            KBA05_SEG10: { name: 'share of more specific cars (Vans, convertables, all-terrains, MUVs etc.)', type: 'number' },
            KBA05_SEG2: { name: 'share of small and very small cars (Ford Fiesta, Ford Ka etc.) in the microcell', type: 'number' },
            KBA05_SEG3: { name: 'share of lowe midclass cars (Ford Focus etc.) in the microcell', type: 'number' },
            KBA05_SEG4: { name: 'share of middle class cars (Ford Mondeo etc.) in the microcell', type: 'number' },
            KBA05_SEG5: { name: 'share of upper middle class cars and upper class cars (BMW5er, BMW7er etc.)', type: 'number' },
            KBA05_SEG6: { name: 'share of upper class cars (BMW 7er etc.) in the microcell', type: 'number' },
            KBA05_SEG7: { name: 'share of all-terrain vehicles and MUVs in the microcell', type: 'number' },
            KBA05_SEG8: { name: 'share of roadster and convertables in the microcell', type: 'number' },
            KBA05_SEG9: { name: 'share of vans in the microcell', type: 'number' },
            KBA05_VORB0: { name: 'share of cars with no preowner', type: 'number' },
            KBA05_VORB1: { name: 'share of cars with one or two preowner', type: 'number' },
            KBA05_VORB2: { name: 'share of cars with more than two preowner', type: 'number' },
            KBA05_ZUL1: { name: 'share of cars built before 1994', type: 'number' },
            KBA05_ZUL2: { name: 'share of cars built between 1994 and 2000', type: 'number' },
            KBA05_ZUL3: { name: 'share of cars built between 2001 and 2002', type: 'number' },
            KBA05_ZUL4: { name: 'share of cars built from 2003 on', type: 'number' },
            KBA13_ALTERHALTER_30: { name: 'share of car owners below 31 within the PLZ8', type: 'number' },
            KBA13_ALTERHALTER_45: { name: 'share of car owners between 31 and 45 within the PLZ8', type: 'number' },
            KBA13_ALTERHALTER_60: { name: 'share of car owners between 46 and 60 within the PLZ8', type: 'number' },
            KBA13_ALTERHALTER_61: { name: 'share of car owners elder than 61 within the PLZ8', type: 'number' },
            KBA13_AUDI: { name: 'share of AUDI within the PLZ8', type: 'number' },
            KBA13_AUTOQUOTE: { name: 'share of cars per household within the PLZ8', type: 'number' },
            KBA13_BJ_1999: { name: 'share of cars built between 1995 and 1999 within the PLZ8', type: 'number' },
            KBA13_BJ_2000: { name: 'share of cars built between 2000 and 2003 within the PLZ8', type: 'number' },
            KBA13_BJ_2004: { name: 'share of cars built before 2004 within the PLZ8', type: 'number' },
            KBA13_BJ_2006: { name: 'share of cars built between 2005 and 2006 within the PLZ8', type: 'number' },
            KBA13_BJ_2008: { name: 'share of cars built in 2008 within the PLZ8', type: 'number' },
            KBA13_BJ_2009: { name: 'share of cars built in 2009 within the PLZ8', type: 'number' },
            KBA13_BMW: { name: 'share of BMW within the PLZ8', type: 'number' },
            KBA13_CCM_1000: { name: 'share of cars with less than 1000ccm within the PLZ8', type: 'number' },
            KBA13_CCM_1200: { name: 'share of cars with 1000ccm to 1199ccm within the PLZ8', type: 'number' },
            KBA13_CCM_1400: { name: 'share of cars with 1200ccm to 1399ccm within the PLZ8', type: 'number' },
            KBA13_CCM_0_1400: { name: 'share of cars with less than 1400ccm within the PLZ8', type: 'number' },
            KBA13_CCM_1500: { name: 'share of cars with 1400ccm to 1499ccm within the PLZ8', type: 'number' },
            KBA13_CCM_1600: { name: 'share of cars with 1500ccm to 1599ccm within the PLZ8', type: 'number' },
            KBA13_CCM_1800: { name: 'share of cars with 1600ccm to 1799ccm within the PLZ8', type: 'number' },
            KBA13_CCM_2000: { name: 'share of cars with 1800ccm to 1999ccm within the PLZ8', type: 'number' },
            KBA13_CCM_2500: { name: 'share of cars with 2000ccm to 2499ccm within the PLZ8', type: 'number' },
            KBA13_CCM_2501: { name: 'share of cars with more than 2500ccm within the PLZ8', type: 'number' },
            KBA13_CCM_3000: { name: 'share of cars with 2500ccm to 2999ccm within the PLZ8', type: 'number' },
            KBA13_CCM_3001: { name: 'share of cars with more than 3000ccm within the PLZ8', type: 'number' },
            KBA13_FAB_ASIEN: { name: 'share of other Asian Manufacturers within the PLZ8', type: 'number' },
            KBA13_FAB_SONSTIGE: { name: 'share of other Manufacturers within the PLZ8', type: 'number' },
            KBA13_FIAT: { name: 'share of FIAT within the PLZ8', type: 'number' },
            KBA13_FORD: { name: 'share of FORD within the PLZ8', type: 'number' },
            KBA13_HALTER_20: { name: 'share of car owners below 21 within the PLZ8', type: 'number' },
            KBA13_HALTER_25: { name: 'share of car owners between 21 and 25 within the PLZ8', type: 'number' },
            KBA13_HALTER_30: { name: 'share of car owners between 26 and 30 within the PLZ8', type: 'number' },
            KBA13_HALTER_35: { name: 'share of car owners between 31 and 35 within the PLZ8', type: 'number' },
            KBA13_HALTER_40: { name: 'share of car owners between 36 and 40 within the PLZ8', type: 'number' },
            KBA13_HALTER_45: { name: 'share of car owners between 41 and 45 within the PLZ8', type: 'number' },
            KBA13_HALTER_50: { name: 'share of car owners between 46 and 50 within the PLZ8', type: 'number' },
            KBA13_HALTER_55: { name: 'share of car owners between 51 and 55 within the PLZ8', type: 'number' },
            KBA13_HALTER_60: { name: 'share of car owners between 56 and 60 within the PLZ8', type: 'number' },
            KBA13_HALTER_65: { name: 'share of car owners between 61 and 65 within the PLZ8', type: 'number' },
            KBA13_HALTER_66: { name: 'share of car owners over 66 within the PLZ8', type: 'number' },
            KBA13_HERST_ASIEN: { name: 'share of Asian Manufacturers within the PLZ8', type: 'number' },
            KBA13_HERST_AUDI_VW: { name: 'share of Volkswagen & Audi within the PLZ8', type: 'number' },
            KBA13_HERST_BMW_BENZ: { name: 'share of BMW & Mercedes Benz within the PLZ8', type: 'number' },
            KBA13_HERST_EUROPA: { name: 'share of European cars within the PLZ8', type: 'number' },
            KBA13_HERST_FORD_OPEL: { name: 'share of Ford & Opel/Vauxhall within the PLZ8', type: 'number' },
            KBA13_HERST_SONST: { name: 'share of other cars within the PLZ8', type: 'number' },
            KBA13_KMH_110: { name: 'share of cars with max speed 110 km/h within the PLZ8', type: 'number' },
            KBA13_KMH_140: { name: 'share of cars with max speed between 110 km/h and 140km/h within the PLZ8', type: 'number' },
            KBA13_KMH_180: { name: 'share of cars with max speed between 110 km/h and 180km/h within the PLZ8', type: 'number' },
            KBA13_KMH_0_140: { name: 'share of cars with max speed 140 km/h within the PLZ8', type: 'number' },
            KBA13_KMH_140_210: { name: 'share of cars with max speed between 140 and 210 km/h within the PLZ8', type: 'number' },
            KBA13_KMH_211: { name: 'share of cars with a greater max speed than 210 km/h within the PLZ8', type: 'number' },
            KBA13_KMH_250: { name: 'share of cars with max speed between 210 and 250 km/h within the PLZ8', type: 'number' },
            KBA13_KMH_251: { name: 'share of cars with a greater max speed than 250 km/h within the PLZ8', type: 'number' },
            KBA13_KRSAQUOT: { name: 'share of cars per household (referred to the county average) - PLZ8', type: 'number' },
            KBA13_KRSHERST_AUDI_VW: { name: 'share of Volkswagen (referred to the county average) - PLZ8', type: 'number' },
            KBA13_KRSHERST_BMW_BENZ: { name: 'share of BMW/Mercedes Benz (referred to the county average) - PLZ8', type: 'number' },
            KBA13_KRSHERST_FORD_OPEL: { name: 'share of FORD/Opel (referred to the county average) - PLZ8', type: 'number' },
            KBA13_KRSSEG_KLEIN: { name: 'share of small cars (referred to the county average) - PLZ8', type: 'number' },
            KBA13_KRSSEG_OBER: { name: 'share of upper class cars (referred to the county average) - PLZ8', type: 'number' },
            KBA13_KRSSEG_VAN: { name: 'share of vans (referred to the county average) - PLZ8', type: 'number' },
            KBA13_KRSZUL_NEU: { name: 'share of newbuilt cars (referred to the county average) - PLZ8', type: 'number' },
            KBA13_KW_30: { name: 'share of cars up to 30 KW engine power - PLZ8', type: 'number' },
            KBA13_KW_40: { name: 'share of cars with an engine power between 31 and 40 KW - PLZ8', type: 'number' },
            KBA13_KW_50: { name: 'share of cars with an engine power between 41 and 50 KW - PLZ8', type: 'number' },
            KBA13_KW_60: { name: 'share of cars with an engine power between 51 and 60 KW - PLZ8', type: 'number' },
            KBA13_KW_0_60: { name: 'share of cars up to 60 KW engine power - PLZ8', type: 'number' },
            KBA13_KW_70: { name: 'share of cars with an engine power between 61 and 70 KW - PLZ8', type: 'number' },
            KBA13_KW_61_120: { name: 'share of cars with an engine power between 61 and 120 KW - PLZ8', type: 'number' },
            KBA13_KW_80: { name: 'share of cars with an engine power between 71 and 80 KW - PLZ8', type: 'number' },
            KBA13_KW_90: { name: 'share of cars with an engine power between 81 and 90 KW - PLZ8', type: 'number' },
            KBA13_KW_110: { name: 'share of cars with an engine power between 91 and 110 KW - PLZ8', type: 'number' },
            KBA13_KW_120: { name: 'share of cars with an engine power between 111 and 120 KW - PLZ8', type: 'number' },
            KBA13_KW_121: { name: 'share of cars with an engine power more than 120 KW - PLZ8', type: 'number' },
            KBA13_MAZDA: { name: 'share of MAZDA within the PLZ8', type: 'number' },
            KBA13_MERCEDES: { name: 'share of MERCEDES within the PLZ8', type: 'number' },
            KBA13_MOTOR: { name: 'most common motor size within the PLZ8', type: 'number' },
            KBA13_NISSAN: { name: 'share of NISSAN within the PLZ8', type: 'number' },
            KBA13_OPEL: { name: 'share of OPEL within the PLZ8', type: 'number' },
            KBA13_PEUGEOT: { name: 'share of PEUGEOT within the PLZ8', type: 'number' },
            KBA13_RENAULT: { name: 'share of RENAULT within the PLZ8', type: 'number' },
            KBA13_SEG_GELAENDEWAGEN: { name: 'share of allterrain within the PLZ8', type: 'number' },
            KBA13_SEG_GROSSRAUMVANS: { name: 'share of big sized vans within the PLZ8', type: 'number' },
            KBA13_SEG_KLEINST: { name: 'share of very small cars (Ford Ka etc.) in the PLZ8', type: 'number' },
            KBA13_SEG_KLEINWAGEN: { name: 'share of small and very small cars (Ford Fiesta, Ford Ka etc.) in the PLZ8', type: 'number' },
            KBA13_SEG_KOMPAKTKLASSE: { name: 'share of lowe midclass cars (Ford Focus etc.) in the PLZ8', type: 'number' },
            KBA13_SEG_MINIVANS: { name: 'share of minivans within the PLZ8', type: 'number' },
            KBA13_SEG_MINIWAGEN: { name: 'share of minicars within the PLZ8', type: 'number' },
            KBA13_SEG_MITTELKLASSE: { name: 'share of middle class cars (Ford Mondeo etc.) in the PLZ8', type: 'number' },
            KBA13_SEG_OBEREMITTELKLASSE: { name: 'share of upper middle class cars and upper class cars (BMW5er, BMW7er etc.)', type: 'number' },
            KBA13_SEG_OBERKLASSE: { name: 'share of upper class cars (BMW 7er etc.) in the PLZ8', type: 'number' },
            KBA13_SEG_SONSTIGE: { name: 'share of other cars within the PLZ8', type: 'number' },
            KBA13_SEG_SPORTWAGEN: { name: 'share of sportscars within the PLZ8', type: 'number' },
            KBA13_SEG_UTILITIES: { name: 'share of MUVs/SUVs within the PLZ8', type: 'number' },
            KBA13_SEG_VAN: { name: 'share of vans within the PLZ8', type: 'number' },
            KBA13_SEG_WOHNMOBILE: { name: 'share of roadmobiles within the PLZ8', type: 'number' },
            KBA13_SITZE_4: { name: 'number of cars with less than 5 seats in the PLZ8', type: 'number' },
            KBA13_SITZE_5: { name: 'number of cars with 5 seats in the PLZ8', type: 'number' },
            KBA13_SITZE_6: { name: 'number of cars with more than 5 seats in the PLZ8', type: 'number' },
            KBA13_TOYOTA: { name: 'share of TOYOTA within the PLZ8', type: 'number' },
            KBA13_VORB_0: { name: 'share of cars with no preowner - PLZ8', type: 'number' },
            KBA13_VORB_1: { name: 'share of cars with 1 preowner - PLZ8', type: 'number' },
            KBA13_VORB_1_2: { name: 'share of cars with 1 or 2 preowner - PLZ8', type: 'number' },
            KBA13_VORB_2: { name: 'share of cars with 2 preowner - PLZ8', type: 'number' },
            KBA13_VORB_3: { name: 'share of cars with 3 or more preowner - PLZ8', type: 'number' },
            KBA13_VW: { name: 'share of VOLKSWAGEN within the PLZ8', type: 'number' },
            KKK: { name: 'purchasing power', type: 'number' },
            NATIONALITAET_KZ: { name: 'nationaltity (scored by prename analysis)', type: 'number' },
            ORTSGR_KLS9: { name: 'size of the community', type: 'number' },
            OST_WEST_KZ: { name: 'flag indicating the former GDR/FRG', type: 'number' },
            PLZ8_ANTG1: { name: 'number of 1-2 family houses in the PLZ8', type: 'number' },
            PLZ8_ANTG2: { name: 'number of 3-5 family houses in the PLZ8', type: 'number' },
            PLZ8_ANTG3: { name: 'number of 6-10 family houses in the PLZ8', type: 'number' },
            PLZ8_ANTG4: { name: 'number of >10 family houses in the PLZ8', type: 'number' },
            PLZ8_GBZ: { name: 'number of buildings within the PLZ8', type: 'number' },
            PLZ8_HHZ: { name: 'number of households within the PLZ8', type: 'number' },
            PRAEGENDE_JUGENDJAHRE: { name: 'dominating movement in the persons youth (avantgarde or mainstream)', type: 'number' },
            REGIOTYP: { name: 'neighbourhood ', type: 'number' },
            RELAT_AB: { name: 'share of unemployed in relation to the county the community belongs to', type: 'number' },
            RETOURTYP_BK_S: { name: 'return type', type: 'number' },
            SEMIO_DOM: { name: 'affinity indicating in what way the person is dominant minded', type: 'number' },
            SEMIO_ERL: { name: 'affinity indicating in what way the person is eventful orientated', type: 'number' },
            SEMIO_FAM: { name: 'affinity indicating in what way the person is familiar minded', type: 'number' },
            SEMIO_KAEM: { name: 'affinity indicating in what way the person is of a fightfull attitude', type: 'number' },
            SEMIO_KRIT: { name: 'affinity indicating in what way the person is critical minded', type: 'number' },
            SEMIO_KULT: { name: 'affinity indicating in what way the person is cultural minded', type: 'number' },
            SEMIO_LUST: { name: 'affinity indicating in what way the person is sensual minded', type: 'number' },
            SEMIO_MAT: { name: 'affinity indicating in what way the person is material minded', type: 'number' },
            SEMIO_PFLICHT: { name: 'affinity indicating in what way the person is dutyfull traditional minded', type: 'number' },
            SEMIO_RAT: { name: 'affinity indicating in what way the person is of a rational mind', type: 'number' },
            SEMIO_REL: { name: 'affinity indicating in what way the person is religious', type: 'number' },
            SEMIO_SOZ: { name: 'affinity indicating in what way the person is social minded', type: 'number' },
            SEMIO_TRADV: { name: 'affinity indicating in what way the person is traditional minded', type: 'number' },
            SEMIO_VERT: { name: 'affinity indicating in what way the person is dreamily', type: 'number' },
            SHOPPER_TYP: { name: 'shopping typology', type: 'number' },
            TITEL_KZ: { name: 'flag whether this person holds an academic title', type: 'number' },
            VERS_TYP: { name: 'insurance typology ', type: 'number' },
            WOHNDAUER_2008: { name: 'length of residence', type: 'number' },
            WOHNLAGE: { name: 'residential-area ', type: 'number' },
            W_KEIT_KIND_HH: { name: 'likelihood of a child present in this household', type: 'number' },
            ZABEOTYP: { name: 'typification of energy consumers', type: 'number' },
            D19_BANKEN_ONLINE_QUOTE_12: { name: 'amount of online transactions within all transactions in the segment bank ', type: 'number' },
            D19_GESAMT_ONLINE_QUOTE_12: { name: 'amount of online transactions within all transactions in the complete file ', type: 'number' },
            D19_VERSAND_ONLINE_QUOTE_12: { name: 'amount of online transactions within all transactions in the segment mail-order ', type: 'number' },
            GEBAEUDETYP_RASTER: { name: 'industrial areas', type: 'number' },
            GEBURTSJAHR: { name: 'year of birth', type: 'number' },
            GFK_URLAUBERTYP: { name: 'vacation habits', type: 'number' },
            GREEN_AVANTGARDE: { name: 'Green avantgarde', type: 'number' },
            KBA13_ANZAHL_PKW: { name: 'number of cars in the PLZ8', type: 'number' },
            KONSUMNAEHE: { name: 'distance from a building to PoS (Point of Sale)', type: 'number' },
            LP_FAMILIE_FEIN: { name: 'familytyp fine', type: 'number' },
            LP_FAMILIE_GROB: { name: 'familytyp rough', type: 'number' },
            LP_LEBENSPHASE_FEIN: { name: 'lifestage fine ', type: 'number' },
            LP_LEBENSPHASE_GROB: { name: 'lifestage rough', type: 'number' },
            LP_STATUS_FEIN: { name: 'social status fine', type: 'number' },
            LP_STATUS_GROB: { name: 'social status rough', type: 'number' },
            MIN_GEBAEUDEJAHR: { name: 'year the building was first mentioned in our database', type: 'number' },
            MOBI_REGIO: { name: 'moving patterns', type: 'number' },
            ONLINE_AFFINITAET: { name: 'online affinity', type: 'number' },
            PLZ8_BAUMAX: { name: 'most common building-type within the PLZ8', type: 'number' }
        }
    };

    public currentConfig: QueryBuilderConfig;

    constructor(
        private formBuilder: FormBuilder
    ) {
        this.queryCtrl = this.formBuilder.control(this.query);
        this.currentConfig = this.config;
    }

    switchModes(event: Event) {
        this.currentConfig = (<HTMLInputElement>event.target).checked ? this.config : this.config;
    }

    changeDisabled(event: Event) {
        (<HTMLInputElement>event.target).checked ? this.queryCtrl.disable() : this.queryCtrl.enable();
    }
}
